from .token_obtain import CustomTokenObtainPairView
from .login import login
from .doctor_list import doctor_list
from .doctor_create import doctor_create
from .doctor_detail import doctor_detail
from .doctor_update import doctor_update
from .doctor_delete import doctor_delete
from .me import me
from .specialties import specialties_list