from .dev_create_user import dev_create_user
from .doctor_create import doctor_create
from .doctor_delete import doctor_delete
from .doctor_detail import doctor_detail
from .doctor_list import doctor_list
from .doctor_update import doctor_update
from .health import health
from .login import login
from .me import me
from .specialties import specialties_list
from .token_obtain import token_obtain
from .token_refresh import token_refresh
