# Generated by Django 6.0.3 on 2026-04-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': [('cancel_appointment', 'Can cancel appointment'), ('reschedule_appointment', 'Can reschedule appointment')]},
        ),
        migrations.AlterModelOptions(
            name='medicalfile',
            options={'permissions': [('download_medicalfile', 'Can download medical file')]},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('export_patient', 'Can export patient data'), ('archive_patient', 'Can archive patient')]},
        ),
    ]
