# Generated by Django 6.0.3 on 2026-04-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_specialty_alter_user_role_user_specialty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("assign_role", "Can assign roles to users"),
                    ("activate_user", "Can activate user"),
                    ("deactivate_user", "Can deactivate user"),
                ]
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
