# Generated by Django 6.0.3 on 2026-04-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_remove_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("assign_group", "Can assign groups to users"),
                    ("activate_user", "Can activate user"),
                    ("deactivate_user", "Can deactivate user"),
                ]
            },
        ),
    ]
