FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

EXPOSE 8002

CMD ["sh", "-c", "python register_consul.py && python manage.py migrate && python manage.py runserver 0.0.0.0:8002"]